export const ONE_MIN_IN_MILLISECONDS = 60000;
export const MIN_STALE_TIME = ONE_MIN_IN_MILLISECONDS * 10;
export const HOUR_STALE_TIME = ONE_MIN_IN_MILLISECONDS * 60;
export const FULL_DAY_STALE_TIME = HOUR_STALE_TIME * 24;
export const HALF_DAY_STALE_TIME = HOUR_STALE_TIME * 12;
export const USER_TOKEN_STORAGE_KEY = "user-token";
