import { IMenue, IMenuItem } from "@/interfaces/IDietPlan";

export const proteinMenuItems: IMenuItem[] = [
  { name: "עוף", oneServing: { spoons: 1, grams: 100 } },
  { name: "בקר", oneServing: { spoons: 1, grams: 100 } },
  { name: "חזיר", oneServing: { spoons: 1, grams: 100 } },
  { name: "כבש", oneServing: { spoons: 1, grams: 100 } },
  { name: "הודו", oneServing: { spoons: 1, grams: 100 } },
  { name: "ברווז", oneServing: { spoons: 1, grams: 100 } },
  { name: "סלמון", oneServing: { spoons: 1, grams: 100 } },
  { name: "טונה", oneServing: { spoons: 1, grams: 100 } },
  { name: "ביצים", oneServing: { spoons: 1, grams: 100 } },
  { name: "טופו", oneServing: { spoons: 1, grams: 100 } },
  { name: "אדממה", oneServing: { spoons: 1, grams: 100 } },
  { name: "עדשים", oneServing: { spoons: 1, grams: 100 } },
  { name: "חומוס", oneServing: { spoons: 1, grams: 100 } },
  { name: "שעועית שחורה", oneServing: { spoons: 1, grams: 100 } },
  { name: "שעועית כליה", oneServing: { spoons: 1, grams: 100 } },
  { name: "שעועית חילבה", oneServing: { spoons: 1, grams: 100 } },
  { name: "שעועית פינטו", oneServing: { spoons: 1, grams: 100 } },
  { name: "קינואה", oneServing: { spoons: 1, grams: 100 } },
  { name: "בוטנים", oneServing: { spoons: 1, grams: 100 } },
  { name: "שקדים", oneServing: { spoons: 1, grams: 100 } },
  { name: "קשיו", oneServing: { spoons: 1, grams: 100 } },
  { name: "אגוזי מלך", oneServing: { spoons: 1, grams: 100 } },
  { name: "אגוזי לוז", oneServing: { spoons: 1, grams: 100 } },
  { name: "גרעיני חמניות", oneServing: { spoons: 1, grams: 100 } },
  { name: "גרעיני דלעת", oneServing: { spoons: 1, grams: 100 } },
  { name: "זרעי צ'יה", oneServing: { spoons: 1, grams: 100 } },
  { name: "זרעי המפ", oneServing: { spoons: 1, grams: 100 } },
  { name: "זרעי פשתן", oneServing: { spoons: 1, grams: 100 } },
  { name: "יוגורט יווני", oneServing: { spoons: 1, grams: 100 } },
  { name: "גבעה גבינה", oneServing: { spoons: 1, grams: 100 } },
  { name: "גאודה", oneServing: { spoons: 1, grams: 100 } },
  { name: "מוצרלה", oneServing: { spoons: 1, grams: 100 } },
  { name: "פרמזן", oneServing: { spoons: 1, grams: 100 } },
  { name: "גבינת ריקוטה", oneServing: { spoons: 1, grams: 100 } },
  { name: "גבינה מעורבבת", oneServing: { spoons: 1, grams: 100 } },
  { name: "נקניק", oneServing: { spoons: 1, grams: 100 } },
  { name: "פפרוני", oneServing: { spoons: 1, grams: 100 } },
  { name: "פסטרמה", oneServing: { spoons: 1, grams: 100 } },
  { name: "בשר מתובל", oneServing: { spoons: 1, grams: 100 } },
  { name: "עגל", oneServing: { spoons: 1, grams: 100 } },
  { name: "גדי", oneServing: { spoons: 1, grams: 100 } },
  { name: "סרדינים", oneServing: { spoons: 1, grams: 100 } },
  { name: "אנשובי", oneServing: { spoons: 1, grams: 100 } },
  { name: "אמנון", oneServing: { spoons: 1, grams: 100 } },
  { name: "טרוטה", oneServing: { spoons: 1, grams: 100 } },
  { name: "לוקוס", oneServing: { spoons: 1, grams: 100 } },
  { name: "בקלה", oneServing: { spoons: 1, grams: 100 } },
  { name: "הדוק", oneServing: { spoons: 1, grams: 100 } },
  { name: "גרופר", oneServing: { spoons: 1, grams: 100 } },
  { name: "קויאר", oneServing: { spoons: 1, grams: 100 } },
  { name: "סייטן", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלבון צמחי ממקור מרקם", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלב סויה", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלב שקדים", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלבון אפונה", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלבון המפ", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלבון מי גבינה", oneServing: { spoons: 1, grams: 100 } },
  { name: "חלבון קזאין", oneServing: { spoons: 1, grams: 100 } },
  { name: "בשר על בסיס צמחי", oneServing: { spoons: 1, grams: 100 } },
];

export const carbMenuItems: IMenuItem[] = [
  { name: "לחם", oneServing: { spoons: 1, grams: 100 } },
  { name: "אורז", oneServing: { spoons: 1, grams: 100 } },
  { name: "פסטה", oneServing: { spoons: 1, grams: 100 } },
  { name: "קינואה", oneServing: { spoons: 1, grams: 100 } },
  { name: "תפוחי אדמה", oneServing: { spoons: 1, grams: 100 } },
  { name: "בטטה", oneServing: { spoons: 1, grams: 100 } },
  { name: "גריסים", oneServing: { spoons: 1, grams: 100 } },
  { name: "כוסמת", oneServing: { spoons: 1, grams: 100 } },
  { name: "לחם מלא", oneServing: { spoons: 1, grams: 100 } },
  { name: "שיבולת שועל", oneServing: { spoons: 1, grams: 100 } },
  { name: "תירס", oneServing: { spoons: 1, grams: 100 } },
];

export const veggatableMenuItems: IMenuItem[] = [
  { name: "גזר", oneServing: { spoons: 1, grams: 100 } },
  { name: "מלפפון", oneServing: { spoons: 1, grams: 100 } },
  { name: "עגבניה", oneServing: { spoons: 1, grams: 100 } },
  { name: "פלפל אדום", oneServing: { spoons: 1, grams: 100 } },
  { name: "פלפל ירוק", oneServing: { spoons: 1, grams: 100 } },
  { name: "ברוקולי", oneServing: { spoons: 1, grams: 100 } },
  { name: "כרובית", oneServing: { spoons: 1, grams: 100 } },
  { name: "חסה", oneServing: { spoons: 1, grams: 100 } },
  { name: "תרד", oneServing: { spoons: 1, grams: 100 } },
  { name: "פטריות", oneServing: { spoons: 1, grams: 100 } },
  { name: "בצל", oneServing: { spoons: 1, grams: 100 } },
  { name: "שום", oneServing: { spoons: 1, grams: 100 } },
  { name: "קישוא", oneServing: { spoons: 1, grams: 100 } },
  { name: "חציל", oneServing: { spoons: 1, grams: 100 } },
  { name: "תירס מתוק", oneServing: { spoons: 1, grams: 100 } },
  { name: "אפונה", oneServing: { spoons: 1, grams: 100 } },
  { name: "שעועית ירוקה", oneServing: { spoons: 1, grams: 100 } },
  { name: "קולורבי", oneServing: { spoons: 1, grams: 100 } },
  { name: "צנון", oneServing: { spoons: 1, grams: 100 } },
  { name: "כרוב", oneServing: { spoons: 1, grams: 100 } },
];

export const fatsMenuItems: IMenuItem[] = [
  { name: "אבוקדו", oneServing: { spoons: 1, grams: 100 } },
  { name: "שמן זית", oneServing: { spoons: 1, grams: 100 } },
  { name: "שמן קוקוס", oneServing: { spoons: 1, grams: 100 } },
  { name: "חמאת בוטנים", oneServing: { spoons: 1, grams: 100 } },
  { name: "חמאת שקדים", oneServing: { spoons: 1, grams: 100 } },
  { name: "שמן חמניות", oneServing: { spoons: 1, grams: 100 } },
  { name: "שמן קנולה", oneServing: { spoons: 1, grams: 100 } },
  { name: "שמן אגוזים", oneServing: { spoons: 1, grams: 100 } },
  { name: "שמן אבוקדו", oneServing: { spoons: 1, grams: 100 } },
  { name: "גרעיני חמניות", oneServing: { spoons: 1, grams: 100 } },
  { name: "גרעיני דלעת", oneServing: { spoons: 1, grams: 100 } },
  { name: "שקדים", oneServing: { spoons: 1, grams: 100 } },
  { name: "אגוזי מלך", oneServing: { spoons: 1, grams: 100 } },
  { name: "קשיו", oneServing: { spoons: 1, grams: 100 } },
  { name: "אגוזי לוז", oneServing: { spoons: 1, grams: 100 } },
  { name: "פיסטוקים", oneServing: { spoons: 1, grams: 100 } },
  { name: "זרעי צ'יה", oneServing: { spoons: 1, grams: 100 } },
  { name: "זרעי פשתן", oneServing: { spoons: 1, grams: 100 } },
  { name: "זרעי המפ", oneServing: { spoons: 1, grams: 100 } },
  { name: "טחינה", oneServing: { spoons: 1, grams: 100 } },
  { name: "חמאה", oneServing: { spoons: 1, grams: 100 } },
  { name: "גי", oneServing: { spoons: 1, grams: 100 } },
  { name: "שומן בקר", oneServing: { spoons: 1, grams: 100 } },
  { name: "שומן חזיר", oneServing: { spoons: 1, grams: 100 } },
];
