import { IMenue, IMenuItem } from "@/interfaces/IDietPlan";

export const proteinMenuItems: IMenuItem[] = [
    { itemName: "עוף", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בקר", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חזיר", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "כבש", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "הודו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "ברווז", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "סלמון", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "טונה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "ביצים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "טופו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אדממה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "עדשים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חומוס", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שעועית שחורה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שעועית כליה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שעועית חילבה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שעועית פינטו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קינואה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בוטנים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שקדים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קשיו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אגוזי מלך", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אגוזי לוז", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גרעיני חמניות", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גרעיני דלעת", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "זרעי צ'יה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "זרעי המפ", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "זרעי פשתן", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "יוגורט יווני", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גבעה גבינה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גאודה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "מוצרלה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פרמזן", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גבינת ריקוטה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גבינה מעורבבת", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "נקניק", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פפרוני", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פסטרמה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בשר מתובל", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "עגל", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גדי", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "סרדינים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אנשובי", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אמנון", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "טרוטה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "לוקוס", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בקלה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "הדוק", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גרופר", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קויאר", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "סייטן", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלבון צמחי ממקור מרקם", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלב סויה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלב שקדים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלבון אפונה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלבון המפ", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלבון מי גבינה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חלבון קזאין", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בשר על בסיס צמחי", oneServing: { spoons: 1, grams: 100 } },
];

export const carbMenuItems: IMenuItem[] = [
    { itemName: "לחם", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אורז", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פסטה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קינואה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "תפוחי אדמה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בטטה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גריסים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "כוסמת", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "לחם מלא", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שיבולת שועל", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "תירס", oneServing: { spoons: 1, grams: 100 } },
]

export const veggatableMenuItems: IMenuItem[] = [
    { itemName: "גזר", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "מלפפון", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "עגבניה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פלפל אדום", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פלפל ירוק", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "ברוקולי", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "כרובית", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חסה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "תרד", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פטריות", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "בצל", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שום", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קישוא", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חציל", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "תירס מתוק", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אפונה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שעועית ירוקה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קולורבי", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "צנון", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "כרוב", oneServing: { spoons: 1, grams: 100 } },
]

export const fatsMenuItems: IMenuItem[] = [
    { itemName: "אבוקדו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שמן זית", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שמן קוקוס", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חמאת בוטנים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חמאת שקדים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שמן חמניות", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שמן קנולה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שמן אגוזים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שמן אבוקדו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גרעיני חמניות", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גרעיני דלעת", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שקדים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אגוזי מלך", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "קשיו", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "אגוזי לוז", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "פיסטוקים", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "זרעי צ'יה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "זרעי פשתן", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "זרעי המפ", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "טחינה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "חמאה", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "גי", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שומן בקר", oneServing: { spoons: 1, grams: 100 } },
    { itemName: "שומן חזיר", oneServing: { spoons: 1, grams: 100 } },
]
