export const tempPresetArr = [
  { name: "ABC-מתחיל" },
  { name: "ABC-בינוני" },
  { name: "ABC-מתקדם" },
  { name: "AB-מתחיל" },
  { name: "AB-בינוני" },
  { name: "AB-מתקדם" },
  { name: "פול בודי-מתחיל" },
  { name: "פול בודי-בינוני" },
  { name: "פול בודי-מתקדם" },
  { name: "ABC-מתחיל" },
  { name: "ABC-בינוני" },
  { name: "ABC-מתקדם" },
  { name: "AB-מתחיל" },
  { name: "AB-בינוני" },
  { name: "AB-מתקדם" },
  { name: "פול בודי-מתחיל" },
  { name: "פול בודי-בינוני" },
  { name: "פול בודי-מתקדם" },
  { name: "ABC-מתחיל" },
  { name: "ABC-בינוני" },
  { name: "ABC-מתקדם" },
  { name: "AB-מתחיל" },
  { name: "AB-בינוני" },
  { name: "AB-מתקדם" },
  { name: "פול בודי-מתחיל" },
  { name: "פול בודי-בינוני" },
  { name: "פול בודי-מתקדם" },
  { name: "ABC-מתחיל" },
  { name: "ABC-בינוני" },
  { name: "ABC-מתקדם" },
  { name: "AB-מתחיל" },
  { name: "AB-בינוני" },
  { name: "AB-מתקדם" },
  { name: "פול בודי-מתחיל" },
  { name: "פול בודי-בינוני" },
  { name: "פול בודי-מתקדם" },
];

export const tempMusclegroupArr = [
  { name: "חזה" },
  { name: "גב" },
  { name: "כתפיים" },
  { name: "רגליים" },
  { name: "בטן" },
  { name: "זרועות" },
  { name: "ירכיים" },
  { name: "שוקיים" },
  { name: "תלת ראשי" },
  { name: "דו ראשי" },
];

export const tempExercisesArr = [
  { name: "לחיצת חזה" },
  { name: "משיכת גב" },
  { name: "לחיצת כתפיים" },
  { name: "סקוואט" },
  { name: "כפיפות בטן" },
  { name: "כפיפת זרועות" },
  { name: "דדליפט" },
  { name: "כפיפת ברכיים" },
  { name: "מתח" },
  { name: "מקבילים" },
];
